spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        gw-flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-gateway-flow.json
            groupId: SENTINEL_GROUP
            rule-type: flow
            data-type: json

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: giraffe-oauth
          uri: lb://giraffe-auth
          predicates:
            - Path=/oauth/**, /api/auth/**
        - id: task-schedule
          uri: lb://task-schedule-svc
          predicates:
            - Path=/api/taskschedule/**
#        - id: front-end
#          uri: http://localhost:4000
#          predicates:
#            - Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取JWT验签公钥请求路径
          jwk-set-uri: 'http://localhost:9000/oauth/getPublicKey'
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: false

logging:
  level:
    cn.ren.marvin.giraffe: debug
    org.springframework.cloud.gateway: warn