spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giraffedata?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
#swagger
swagger:
  enabled: true

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: false

#feign client&compression
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

ribbon:
  eager-load:
    enabled: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


