spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        gw-flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-gateway-flow.json
            groupId: SENTINEL_GROUP
            rule-type: flow
            data-type: json
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: auth-giraffe
          uri: lb://auth-giraffe
          predicates:
            - Path=/oauth/**
        - id: task-schedule
          uri: lb://task-schedule-svc
          predicates:
            - Path=/taskschedule/**

        - id: baidu-go
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix= 1
        - id: front-end
          uri: http://localhost:8001
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: debug