server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zendata?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 1
logging:
  level:
    root: WARN
    cn.ren.marvin: INFO
    org.springframework.security: WARN
    org.springframework.web: ERROR
    org.hibernate: WARN
